baseURL = "https://mattwebb.io/"
languageCode = "en-us"
title = "Matt Webb | Software Engineer"
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  sbadges = "?longCache=true&style=for-the-badge&colorA=efefef&logo="
  smallsbadges = "?longCache=true&style=for-the-badge&logo="