baseURL = "https://mattwebb.io/"
languageCode = "en-us"
title = "Matt Webb | Software Engineer"
[params]
  sbadges = "?longCache=true&style=for-the-badge&colorA=efefef&logo="
  smallsbadges = "?longCache=true&style=for-the-badge&logo="